# -*- coding: utf-8 -*-
"""WeatherTask1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KRKzwjDP3mgeBecze_OHKEAf6bUQTzfg
"""

# CodTech Task 1 - Weather Data Visualization

import requests
import matplotlib.pyplot as plt

# Replace with your actual API key from OpenWeatherMap
API_KEY = "a06e5ece5d4a628c9e7ae96d931dcde5"

# List of Indian cities to check weather for
cities = ["Bangalore", "Delhi", "Mumbai", "Chennai", "Kolkata"]
temperatures = []

for city in cities:
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"
    response = requests.get(url)
    data = response.json()

    if response.status_code == 200:
        temp = data['main']['temp']
        temperatures.append(temp)
        print(f"{city}: {temp}°C")
    else:
        temperatures.append(None)
        print(f"Error fetching data for {city}")

# Plotting the temperature bar chart
plt.figure(figsize=(10, 5))
plt.bar(cities, temperatures, color='skyblue')
plt.xlabel("City")
plt.ylabel("Temperature (°C)")
plt.title("Current Temperature in Indian Cities")
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()